NUMBER_OF_ROWS = 50
NUMBER_OF_COLUMNS = 50
CELL_SIZE = 10

FPS = 60
SCREEN_HEIGHT = CELL_SIZE * NUMBER_OF_ROWS
SCREEN_WIDTH = CELL_SIZE * NUMBER_OF_COLUMNS

CELL_COLOR = (128, 128, 128)
BACKGROUND_COLOR = (0, 0, 0)
