NUMBER_OF_ROWS = 100
NUMBER_OF_COLUMNS = 100
CELL_SIZE = 10

FPS = 60
SCREEN_HEIGHT = CELL_SIZE * NUMBER_OF_ROWS
SCREEN_WIDTH = CELL_SIZE * NUMBER_OF_COLUMNS

CELL_COLOR = (51, 153, 255)
BACKGROUND_COLOR = (0, 0, 0)

RANDOM_INIT = 0.5
AMOUNT_OF_ITERATIONS = 10
